#![allow(unexpected_cfgs)]
//! Coorwa launch curve.
//!
//! A launch here is one token, one curve and one tax. The program mints a Token-2022 token whose
//! transfer fee is chosen by the creator and then frozen forever, sells it against COOK on a
//! constant-product curve with virtual reserves, and at a fixed amount raised hands the token to a
//! real pool. The tax is what pays the token's holders, so it has to be live from the very first
//! trade: that is the whole reason a buy here moves real tokens instead of a program-side balance.
//!
//! Three properties are load bearing, and each one is a thing a buyer can check on chain rather
//! than a promise on a web page:
//!
//!   - **The tax can never change.** `transfer_fee_config_authority` is set to `None` at the moment
//!     the mint is created, not renounced later, so there is no window in which anyone could raise
//!     it. The rate a launch opens with is the rate it dies with.
//!   - **The supply is fixed and the mint is sealed.** The whole supply is minted once, in the same
//!     instruction, and the mint authority is dropped before the instruction returns. There is no
//!     freeze authority and no permanent delegate, so nobody can mint, freeze or seize.
//!   - **The curve cannot be drained.** Quote only ever leaves through `sell`, priced by the same
//!     invariant that let it in, and the fees the program keeps are tracked separately from the
//!     reserve so that claiming them can never eat into what sellers are owed.
//!
//! What the program deliberately does *not* do: hold anyone's tokens for them. There is no claim
//! step. A buy delivers the token to the buyer's own account in the same transaction, which is what
//! makes the tax collectible from the first trade and also means a curve that never graduates still
//! paid its holders along the way.
//!
//! ## Why the sell path reads a balance instead of doing arithmetic
//!
//! Every transfer of a taxed mint arrives short: the fee is withheld in the destination account, so
//! when a seller sends the curve 1,000 tokens the vault's spendable balance goes up by less. The
//! amount the curve must price is the amount that actually arrived, and the only source of truth
//! for that is the vault itself. So `sell` reloads the vault and prices the trade off the delta.
//! Recomputing the fee from the mint's config would give the same answer today and a wrong answer
//! the day anything about that config surprises us.
//!
//! Buys need no such care. The base leaving the vault is taxed too, but the fee is withheld in the
//! *buyer's* account, so the vault's side of the arithmetic is exact and the buyer simply receives
//! the rate less than the curve sent. The client shows that, and `min_base_out` is checked against
//! what the curve sends, not against what the buyer nets.

use anchor_lang::prelude::*;
use anchor_lang::solana_program::instruction::{AccountMeta, Instruction};
use anchor_lang::solana_program::program::{invoke, invoke_signed};
use anchor_lang::system_program;
use anchor_spl::associated_token::AssociatedToken;
use anchor_spl::token_2022::{spl_token_2022, Token2022};
use anchor_spl::token_interface::{
    self, Mint, TokenAccount, TokenInterface, TokenMetadataInitialize,
};

// The pubkey of target/deploy/corwa_launch-keypair.json, generated by the first build. That file is
// the deploy identity, so it is the one thing here that must be backed up before the program ever
// goes out: lose it and this address can never be deployed to again.
declare_id!("DT7Jds9LADV82pdKyDBcYPDfb7vaKvHcbyEG48zxuvZq");

pub const CONFIG_SEED: &[u8] = b"config";
pub const CURVE_SEED: &[u8] = b"curve";
/// Seed of the account that actually holds a curve's assets. See `VaultAuthority` below.
pub const AUTHORITY_SEED: &[u8] = b"authority";

/// A live curve trades. A graduated one has hit its target and is closed to trading, waiting for
/// someone to open its pool. A pooled one is done: its liquidity is locked on Cookiebox forever and
/// all that is left to do is collect fees.
pub const STATE_LIVE: u8 = 0;
pub const STATE_GRADUATED: u8 = 1;
pub const STATE_POOLED: u8 = 2;

/// Basis-point denominator, used for the curve fee, the tax tiers and the LP split alike.
pub const BPS: u128 = 10_000;

/// A cap on the curve fee that exists so a config mistake cannot produce a launch nobody can trade
/// out of. Five percent is already far past anything reasonable.
pub const MAX_CURVE_FEE_BPS: u16 = 500;

/// The tax is a percentage and stays one at any size, so the absolute cap Token-2022 also carries
/// is set out of the way rather than left to do something surprising to a whale.
pub const MAX_TRANSFER_FEE: u64 = u64::MAX;

/// Room for fields we have not thought of yet, so adding one later does not move every field after
/// it and invalidate every client at once.
pub const RESERVED: usize = 64;

/// Why a curve's money does not live under the curve account.
///
/// Two constraints meet here. Cookiebox's pool program takes the tokens for a new pool from accounts
/// owned by whoever pays the rent, so one account has to be both the token authority and the rent
/// payer. And the system program refuses to move lamports out of an account that carries data, which
/// the curve account does.
///
/// So every curve has a second address, `[b"authority", mint]`, that holds nothing but lamports and
/// owns the two vaults. It can pay rent because it has no data, it can sign for the vaults because
/// it is a PDA of this program, and the curve account next to it stays pure bookkeeping.
pub struct VaultAuthority;

/// Cookiebox's pool program, a cp-amm fork, and its one fixed authority account. Both are chain
/// furniture rather than settings: a different pool program would be a different product.
pub mod damm {
    use anchor_lang::prelude::*;

    #[constant]
    pub const PROGRAM_ID: Pubkey = pubkey!("DAMMjDCEFTDkt7ywazZS8GoaLtjb3HaJo3pLbf64xrPY");
    #[constant]
    pub const POOL_AUTHORITY: Pubkey = pubkey!("8WYfVSBcP3T1amRNmTnLfzYd44VDjGpw1jZxrEL8638o");

    /// Anchor discriminators of the three instructions this program calls.
    pub const IX_INITIALIZE_POOL: [u8; 8] = [0x5f, 0xb4, 0x0a, 0xac, 0x54, 0xae, 0xe8, 0x28];
    pub const IX_PERMANENT_LOCK: [u8; 8] = [0xa5, 0xb0, 0x7d, 0x06, 0xe7, 0xab, 0xba, 0xd5];
    pub const IX_CLAIM_POSITION_FEE: [u8; 8] = [0xb4, 0x26, 0x9a, 0x11, 0x85, 0x21, 0xa2, 0xd3];

    /// The bounds of a full-range position, in the same Q64.64 form the pool stores its price in.
    pub const MIN_SQRT_PRICE: u128 = 4_295_048_016;
    pub const MAX_SQRT_PRICE: u128 = 79_226_673_521_066_979_257_578_248_091;
}

#[program]
pub mod corwa_launch {
    use super::*;

    /// Create the one config every launch reads. Whoever signs this owns the platform settings.
    pub fn initialize_config(ctx: Context<InitializeConfig>, params: ConfigParams) -> Result<()> {
        params.validate()?;

        let config = &mut ctx.accounts.config;
        config.authority = ctx.accounts.authority.key();
        config.quote_mint = ctx.accounts.quote_mint.key();
        config.bump = ctx.bumps.config;
        config.launch_count = 0;
        params.apply(config);

        emit!(ConfigInitialized {
            config: config.key(),
            authority: config.authority,
            quote_mint: config.quote_mint,
        });
        Ok(())
    }

    /// Change the settings future launches will read.
    ///
    /// A live curve is untouched by this on purpose: every number that prices a trade is copied
    /// onto the curve when it is created, so nobody's launch can be repriced under them.
    pub fn update_config(ctx: Context<UpdateConfig>, params: ConfigParams) -> Result<()> {
        params.validate()?;
        params.apply(&mut ctx.accounts.config);

        emit!(ConfigUpdated { config: ctx.accounts.config.key() });
        Ok(())
    }

    /// Mint a launch token and open its curve.
    ///
    /// Everything irreversible about the token happens here: the extensions it will carry, the tax
    /// it will charge, its whole supply, and the loss of the mint authority. Nothing later in the
    /// program's life can add to that list.
    pub fn launch(ctx: Context<Launch>, params: LaunchParams) -> Result<()> {
        let config = &ctx.accounts.config;
        require!(!config.paused, LaunchError::LaunchesPaused);
        require!(config.tax_allowed(params.tax_bps), LaunchError::TaxTierNotOffered);
        require!(!params.name.is_empty() && params.name.len() <= 32, LaunchError::BadMetadata);
        require!(!params.symbol.is_empty() && params.symbol.len() <= 10, LaunchError::BadMetadata);
        require!(params.uri.len() <= 200, LaunchError::BadMetadata);

        let mint_key = ctx.accounts.mint.key();
        let curve_bump = ctx.bumps.curve;
        let seeds: &[&[u8]] = &[CURVE_SEED, mint_key.as_ref(), &[curve_bump]];

        create_taxed_mint(&ctx, params.tax_bps)?;
        write_metadata(&ctx, &params, seeds)?;
        open_vaults(&ctx)?;
        mint_supply_and_seal(&ctx, config.total_supply(), seeds)?;

        let curve = &mut ctx.accounts.curve;
        curve.config = config.key();
        curve.creator = ctx.accounts.creator.key();
        curve.mint = mint_key;
        curve.base_vault = ctx.accounts.base_vault.key();
        curve.quote_vault = ctx.accounts.quote_vault.key();
        curve.virtual_base = config.virtual_base;
        curve.virtual_quote = config.virtual_quote;
        curve.sale_base = config.sale_base;
        curve.migration_base = config.migration_base;
        curve.graduation_quote = config.graduation_quote;
        curve.base_sold = 0;
        curve.quote_raised = 0;
        curve.fees_quote = 0;
        curve.tax_bps = params.tax_bps;
        curve.curve_fee_bps = config.curve_fee_bps;
        curve.creator_lp_share_bps = config.creator_lp_share_bps;
        curve.state = STATE_LIVE;
        curve.created_at = Clock::get()?.unix_timestamp;
        curve.bump = curve_bump;

        let config = &mut ctx.accounts.config;
        config.launch_count = config.launch_count.saturating_add(1);

        emit!(Launched {
            curve: ctx.accounts.curve.key(),
            mint: mint_key,
            creator: ctx.accounts.creator.key(),
            tax_bps: params.tax_bps,
            symbol: params.symbol,
        });
        Ok(())
    }

    /// Buy base with quote.
    ///
    /// `max_quote_in` is a ceiling rather than an amount. A curve that is close to its threshold
    /// takes only what it has room for and leaves the rest in the buyer's account, which is how the
    /// raise lands on the threshold exactly instead of overshooting it and needing a refund path.
    pub fn buy(ctx: Context<Trade>, max_quote_in: u64, min_base_out: u64) -> Result<()> {
        let curve = &ctx.accounts.curve;
        require!(curve.state == STATE_LIVE, LaunchError::CurveClosed);
        require!(max_quote_in > 0, LaunchError::ZeroAmount);

        let room = curve
            .graduation_quote
            .checked_sub(curve.quote_raised)
            .ok_or(LaunchError::MathOverflow)?;
        require!(room > 0, LaunchError::CurveClosed);

        let mint_key = curve.mint;
        let authority_bump = ctx.bumps.vault_authority;

        let (quote_taken, fee, net) = math::split_buy(max_quote_in, curve.curve_fee_bps, room)?;
        require!(net > 0, LaunchError::AmountTooSmall);

        let base_out = math::swap_out(curve.reserve_base()?, curve.reserve_quote()?, net as u128)?;
        let base_out = u64::try_from(base_out).map_err(|_| LaunchError::MathOverflow)?;
        require!(base_out >= min_base_out, LaunchError::SlippageExceeded);
        require!(base_out > 0, LaunchError::AmountTooSmall);

        let unsold = curve
            .sale_base
            .checked_sub(curve.base_sold)
            .ok_or(LaunchError::MathOverflow)?;
        require!(base_out <= unsold, LaunchError::CurveExhausted);

        // Quote in first: if the buyer cannot pay, nothing else should have happened.
        token_interface::transfer_checked(
            ctx.accounts.quote_in_ctx(),
            quote_taken,
            ctx.accounts.quote_mint.decimals,
        )?;

        let seeds: &[&[u8]] = &[AUTHORITY_SEED, mint_key.as_ref(), &[authority_bump]];
        let signer: &[&[&[u8]]] = &[seeds];
        token_interface::transfer_checked(
            ctx.accounts.base_out_ctx(signer),
            base_out,
            ctx.accounts.mint.decimals,
        )?;

        let curve = &mut ctx.accounts.curve;
        curve.quote_raised = curve.quote_raised.saturating_add(net);
        curve.fees_quote = curve.fees_quote.saturating_add(fee);
        curve.base_sold = curve.base_sold.saturating_add(base_out);
        if curve.quote_raised >= curve.graduation_quote {
            curve.state = STATE_GRADUATED;
        }

        emit!(Traded {
            curve: curve.key(),
            mint: curve.mint,
            trader: ctx.accounts.trader.key(),
            is_buy: true,
            quote_amount: quote_taken,
            base_amount: base_out,
            fee,
            quote_raised: curve.quote_raised,
            base_sold: curve.base_sold,
            graduated: curve.state == STATE_GRADUATED,
        });
        Ok(())
    }

    /// Sell base back to the curve.
    ///
    /// The tax is charged on the way in, so the curve prices what the vault actually received. A
    /// seller therefore pays the tax once, in the token, and again never: `min_quote_out` is checked
    /// against the quote they will really see.
    pub fn sell(ctx: Context<Trade>, base_in: u64, min_quote_out: u64) -> Result<()> {
        let curve = &ctx.accounts.curve;
        require!(curve.state == STATE_LIVE, LaunchError::CurveClosed);
        require!(base_in > 0, LaunchError::ZeroAmount);

        let before = ctx.accounts.base_vault.amount;
        token_interface::transfer_checked(
            ctx.accounts.base_in_ctx(),
            base_in,
            ctx.accounts.mint.decimals,
        )?;
        ctx.accounts.base_vault.reload()?;
        let received = ctx
            .accounts
            .base_vault
            .amount
            .checked_sub(before)
            .ok_or(LaunchError::MathOverflow)?;
        require!(received > 0, LaunchError::AmountTooSmall);

        let curve = &ctx.accounts.curve;
        let mint_key = curve.mint;
        let authority_bump = ctx.bumps.vault_authority;
        let gross = math::swap_out(curve.reserve_quote()?, curve.reserve_base()?, received as u128)?;
        let gross = u64::try_from(gross).map_err(|_| LaunchError::MathOverflow)?;
        require!(gross > 0, LaunchError::AmountTooSmall);
        require!(gross <= curve.quote_raised, LaunchError::CurveInsolvent);

        let fee = math::bps_of(gross, curve.curve_fee_bps)?;
        let to_seller = gross.checked_sub(fee).ok_or(LaunchError::MathOverflow)?;
        require!(to_seller >= min_quote_out, LaunchError::SlippageExceeded);

        let seeds: &[&[u8]] = &[AUTHORITY_SEED, mint_key.as_ref(), &[authority_bump]];
        let signer: &[&[&[u8]]] = &[seeds];
        token_interface::transfer_checked(
            ctx.accounts.quote_out_ctx(signer),
            to_seller,
            ctx.accounts.quote_mint.decimals,
        )?;

        let curve = &mut ctx.accounts.curve;
        curve.quote_raised = curve.quote_raised.saturating_sub(gross);
        curve.fees_quote = curve.fees_quote.saturating_add(fee);
        curve.base_sold = curve
            .base_sold
            .checked_sub(received)
            .ok_or(LaunchError::MathOverflow)?;

        emit!(Traded {
            curve: curve.key(),
            mint: curve.mint,
            trader: ctx.accounts.trader.key(),
            is_buy: false,
            quote_amount: to_seller,
            base_amount: received,
            fee,
            quote_raised: curve.quote_raised,
            base_sold: curve.base_sold,
            graduated: false,
        });
        Ok(())
    }

    /// Send the curve fees collected so far to the config's fee recipient.
    ///
    /// Permissionless, because the destination is fixed by the config rather than by whoever calls,
    /// and a lost operator key should not strand the platform's own revenue.
    pub fn claim_curve_fees(ctx: Context<ClaimCurveFees>) -> Result<()> {
        let curve = &ctx.accounts.curve;
        let amount = curve.fees_quote;
        require!(amount > 0, LaunchError::NothingToClaim);

        let mint_key = curve.mint;
        let seeds: &[&[u8]] = &[AUTHORITY_SEED, mint_key.as_ref(), &[ctx.bumps.vault_authority]];
        let signer: &[&[&[u8]]] = &[seeds];
        token_interface::transfer_checked(
            ctx.accounts.transfer_ctx(signer),
            amount,
            ctx.accounts.quote_mint.decimals,
        )?;

        let curve = &mut ctx.accounts.curve;
        curve.fees_quote = 0;

        emit!(FeesClaimed { curve: curve.key(), mint: curve.mint, amount });
        Ok(())
    }

    /// Open the token's pool on Cookiebox and lock the liquidity there forever.
    ///
    /// Permissionless, because a curve that has hit its target should not wait on us. Whoever sends
    /// it pays the rent for the pool accounts, which is why the vault authority needs lamports in it
    /// by the time this runs: a plain transfer in the same transaction is enough, and the crank that
    /// normally does this is ours.
    ///
    /// `liquidity` and `sqrt_price` are worked out by the caller, because reproducing the pool's own
    /// fixed-point liquidity maths here would cost more than it buys. What the program does instead
    /// is check the result: the price has to match the price the curve closed at, and the amounts the
    /// pool actually took have to match the reserve and the migration supply. A caller who passes
    /// bad numbers gets a failed transaction, not a bad pool.
    pub fn graduate(ctx: Context<Graduate>, liquidity: u128, sqrt_price: u128) -> Result<()> {
        let curve = &ctx.accounts.curve;
        require!(curve.state == STATE_GRADUATED, LaunchError::NotGraduated);
        require!(liquidity > 0, LaunchError::ZeroAmount);

        // The pool asks for the amount it wants to *hold* and the token program takes the tax on
        // top, so the base that reaches the pool is the migration supply less the tax. Pricing the
        // pool off the gross would ask the vault for more base than a fully sold curve has left.
        let seeded_base = math::net_of_tax(curve.migration_base, curve.tax_bps)?;
        let expected = math::expected_sqrt_price(curve.quote_raised, seeded_base)?;
        require!(math::within_one_percent(sqrt_price, expected), LaunchError::PriceMismatch);

        let mint_key = curve.mint;
        let authority_bump = ctx.bumps.vault_authority;
        let quote_raised = curve.quote_raised;
        let migration_base = curve.migration_base;

        let base_before = ctx.accounts.base_vault.amount;
        let quote_before = ctx.accounts.quote_vault.amount;

        let seeds: &[&[u8]] = &[AUTHORITY_SEED, mint_key.as_ref(), &[authority_bump]];
        ctx.accounts.initialize_pool(liquidity, sqrt_price, seeds)?;

        ctx.accounts.base_vault.reload()?;
        ctx.accounts.quote_vault.reload()?;
        let base_spent = base_before
            .checked_sub(ctx.accounts.base_vault.amount)
            .ok_or(LaunchError::MathOverflow)?;
        let quote_spent = quote_before
            .checked_sub(ctx.accounts.quote_vault.amount)
            .ok_or(LaunchError::MathOverflow)?;

        // The whole reserve goes into the pool, give or take the rounding the pool does on the way
        // in. Anything less would be liquidity quietly left behind.
        require!(quote_spent <= quote_raised, LaunchError::SeedOutOfRange);
        require!(
            (quote_spent as u128) * 1000 >= (quote_raised as u128) * 999,
            LaunchError::SeedOutOfRange
        );
        // What leaves the vault is the migration supply, tax included. A percent of slack covers the
        // rounding on both sides of that, and nothing covers a caller trying to seed the pool with
        // more of the supply than the launch set aside.
        let slack = migration_base / 100;
        require!(
            base_spent <= migration_base.saturating_add(slack),
            LaunchError::SeedOutOfRange
        );
        require!(
            base_spent >= migration_base.saturating_sub(slack.saturating_mul(2)),
            LaunchError::SeedOutOfRange
        );

        ctx.accounts.lock_liquidity(liquidity, seeds)?;

        // Everything the curve did not sell and the pool did not take is burned. A launch's supply
        // is what people actually hold plus what backs the pool, and nothing is kept in reserve for
        // anyone, including us.
        let leftover = ctx.accounts.base_vault.amount;
        if leftover > 0 {
            ctx.accounts.burn_leftover(leftover, seeds)?;
        }

        let curve = &mut ctx.accounts.curve;
        curve.state = STATE_POOLED;
        curve.position_nft_mint = ctx.accounts.position_nft_mint.key();

        emit!(Graduated {
            curve: curve.key(),
            mint: curve.mint,
            pool: ctx.accounts.pool.key(),
            position: ctx.accounts.position.key(),
            position_nft_mint: curve.position_nft_mint,
            quote_seeded: quote_spent,
            base_seeded: base_spent,
            burned: leftover,
            liquidity,
        });
        Ok(())
    }

    /// Collect the graduated pool's fees and split them.
    ///
    /// The position is locked forever, so this is the only thing it will ever produce. The split is
    /// enforced here rather than promised anywhere: the creator's share is paid in the same
    /// instruction that collects it, and neither we nor they can be paid without the other.
    ///
    /// Permissionless for the same reason as the curve fees: both destinations are fixed before the
    /// instruction runs.
    pub fn claim_pool_fees(ctx: Context<ClaimPoolFees>) -> Result<()> {
        let curve = &ctx.accounts.curve;
        require!(curve.state == STATE_POOLED, LaunchError::NotPooled);
        require!(
            curve.position_nft_mint == ctx.accounts.position_nft_mint.key(),
            LaunchError::WrongPosition
        );

        let mint_key = curve.mint;
        let authority_bump = ctx.bumps.vault_authority;
        let creator_share_bps = curve.creator_lp_share_bps;

        let base_before = ctx.accounts.base_vault.amount;
        let quote_before = ctx.accounts.quote_vault.amount;

        let seeds: &[&[u8]] = &[AUTHORITY_SEED, mint_key.as_ref(), &[authority_bump]];
        ctx.accounts.claim_position_fee(seeds)?;

        ctx.accounts.base_vault.reload()?;
        ctx.accounts.quote_vault.reload()?;
        let base_fees = ctx
            .accounts
            .base_vault
            .amount
            .checked_sub(base_before)
            .ok_or(LaunchError::MathOverflow)?;
        let quote_fees = ctx
            .accounts
            .quote_vault
            .amount
            .checked_sub(quote_before)
            .ok_or(LaunchError::MathOverflow)?;
        require!(base_fees > 0 || quote_fees > 0, LaunchError::NothingToClaim);

        // Only what this claim brought in is moved on, so a curve's own unclaimed trading fees and
        // any dust already sitting in the vaults are left where they are.
        let creator_quote = math::bps_of(quote_fees, creator_share_bps)?;
        let platform_quote = quote_fees
            .checked_sub(creator_quote)
            .ok_or(LaunchError::MathOverflow)?;
        let creator_base = math::bps_of(base_fees, creator_share_bps)?;
        let platform_base = base_fees
            .checked_sub(creator_base)
            .ok_or(LaunchError::MathOverflow)?;

        ctx.accounts.pay_out(creator_quote, platform_quote, creator_base, platform_base, seeds)?;

        emit!(PoolFeesClaimed {
            curve: ctx.accounts.curve.key(),
            mint: mint_key,
            quote_to_creator: creator_quote,
            quote_to_platform: platform_quote,
            base_to_creator: creator_base,
            base_to_platform: platform_base,
        });
        Ok(())
    }
}

// --- the curve itself ----------------------------------------------------------------------------

/// Pure arithmetic, kept out of the instruction bodies so it can be tested without a validator.
pub mod math {
    use super::{LaunchError, BPS};
    use anchor_lang::prelude::*;

    /// `bps` of `amount`, rounded down.
    pub fn bps_of(amount: u64, bps: u16) -> Result<u64> {
        let v = (amount as u128)
            .checked_mul(bps as u128)
            .ok_or(LaunchError::MathOverflow)?
            / BPS;
        u64::try_from(v).map_err(|_| LaunchError::MathOverflow.into())
    }

    /// One side of a constant-product swap: `reserve_out * amount_in / (reserve_in + amount_in)`.
    ///
    /// Rounded down, which is the direction that leaves the rounding dust in the curve rather than
    /// in the trader's pocket. Both legs use this, because a buy and a sell are the same trade read
    /// from opposite ends.
    pub fn swap_out(reserve_out: u128, reserve_in: u128, amount_in: u128) -> Result<u128> {
        let denominator = reserve_in
            .checked_add(amount_in)
            .ok_or(LaunchError::MathOverflow)?;
        require!(denominator > 0, LaunchError::MathOverflow);
        let numerator = reserve_out
            .checked_mul(amount_in)
            .ok_or(LaunchError::MathOverflow)?;
        Ok(numerator / denominator)
    }

    /// Work out what a buy actually costs, given how much room the curve has left.
    ///
    /// Returns `(quote_taken, fee, net)`: what leaves the buyer's account, what the platform keeps,
    /// and what reaches the reserve. When the curve is nearly full the whole triple shrinks so that
    /// `net` lands exactly on the remaining room, which is how a raise ends on its threshold rather
    /// than past it.
    pub fn split_buy(max_quote_in: u64, fee_bps: u16, room: u64) -> Result<(u64, u64, u64)> {
        let fee = bps_of(max_quote_in, fee_bps)?;
        let net = max_quote_in
            .checked_sub(fee)
            .ok_or(LaunchError::MathOverflow)?;
        if net <= room {
            return Ok((max_quote_in, fee, net));
        }

        // Scale the fee back to the part of the trade that is actually used. `fee_bps` is a share
        // of the gross, so the fee on a net of `room` is `room * bps / (BPS - bps)`.
        let denominator = BPS
            .checked_sub(fee_bps as u128)
            .ok_or(LaunchError::MathOverflow)?;
        require!(denominator > 0, LaunchError::MathOverflow);
        let fee = u64::try_from(
            (room as u128)
                .checked_mul(fee_bps as u128)
                .ok_or(LaunchError::MathOverflow)?
                / denominator,
        )
        .map_err(|_| LaunchError::MathOverflow)?;
        let taken = room.checked_add(fee).ok_or(LaunchError::MathOverflow)?;
        Ok((taken, fee, room))
    }

    /// The price the pool has to open at, as sqrt(quote per base) in Q64.64, which is how the pool
    /// program stores a price.
    ///
    /// `sqrt(q / b) * 2^64` is the same number as `sqrt((q << 64) / b) << 32`, and the second form
    /// stays inside a u128 for every amount this program can hold. The shift costs the low 32 bits of
    /// a 128-bit value, which is far below the precision any pool cares about.
    pub fn expected_sqrt_price(quote: u64, base: u64) -> Result<u128> {
        require!(quote > 0 && base > 0, LaunchError::ZeroAmount);
        let scaled = ((quote as u128) << 64) / (base as u128);
        Ok(isqrt(scaled) << 32)
    }

    /// Integer square root, by the usual bit-by-bit method. No floats in a program.
    pub fn isqrt(value: u128) -> u128 {
        if value < 2 {
            return value;
        }
        let mut bit = 1u128 << ((127 - value.leading_zeros()) & !1);
        let mut root = 0u128;
        let mut rest = value;
        while bit != 0 {
            let candidate = root + bit;
            root >>= 1;
            if rest >= candidate {
                rest -= candidate;
                root += bit;
            }
            bit >>= 2;
        }
        root
    }

    /// True when two prices are within one percent of each other, which is the slack the caller gets
    /// for its own rounding when it works out the pool's opening price.
    pub fn within_one_percent(a: u128, b: u128) -> bool {
        let (lo, hi) = if a < b { (a, b) } else { (b, a) };
        match hi.checked_sub(lo) {
            Some(gap) => gap.saturating_mul(100) <= hi,
            None => false,
        }
    }

    /// The transfer tax on an amount, rounded up, which is how Token-2022 computes it. The curve fee
    /// rounds down because it rounds in the curve's favour; a transfer fee is not ours to round.
    pub fn tax_of(amount: u64, bps: u16) -> Result<u64> {
        if bps == 0 || amount == 0 {
            return Ok(0);
        }
        let v = (amount as u128)
            .checked_mul(bps as u128)
            .ok_or(LaunchError::MathOverflow)?
            .div_ceil(BPS);
        u64::try_from(v).map_err(|_| LaunchError::MathOverflow.into())
    }

    /// What arrives when `amount` is sent and a transfer fee of `bps` is taken out of it on the way.
    pub fn net_of_tax(amount: u64, bps: u16) -> Result<u64> {
        let fee = tax_of(amount, bps)?;
        amount.checked_sub(fee).ok_or(LaunchError::MathOverflow.into())
    }

    #[cfg(test)]
    mod tests {
        use super::*;

        /// The defaults this program is meant to launch with: 1B supply at 6 decimals, 80% of it on
        /// the curve, 1,000,000 COOK to graduate, and virtual reserves that make the price rise 16x
        /// from open to graduation.
        const SALE_BASE: u128 = 800_000_000_000_000; // 800M at 6 decimals
        const GRADUATION: u128 = 1_000_000_000_000_000; // 1M COOK at 9 decimals
        const VIRTUAL_QUOTE: u128 = GRADUATION / 3;
        const VIRTUAL_BASE: u128 = SALE_BASE * 4 / 3;

        fn buy(sold: u128, raised: u128, net: u128) -> u128 {
            swap_out(VIRTUAL_BASE - sold, VIRTUAL_QUOTE + raised, net).unwrap()
        }

        #[test]
        fn fee_is_a_share_of_the_gross() {
            assert_eq!(bps_of(1_000_000, 100).unwrap(), 10_000);
            assert_eq!(bps_of(1, 100).unwrap(), 0);
            assert_eq!(bps_of(u64::MAX, 0).unwrap(), 0);
        }

        #[test]
        fn the_whole_sale_supply_fits_in_the_raise() {
            // Selling into the curve until the threshold is reached must not need more base than
            // the curve has to sell, or a launch could hit its target with nothing left to deliver.
            let sold = buy(0, 0, GRADUATION);
            assert!(sold <= SALE_BASE, "sold {sold} > sale supply {SALE_BASE}");
            // and it should be close to the whole thing, or the curve stops early and burns most
            // of its supply
            assert!(sold * 100 / SALE_BASE >= 99, "only {} percent sold", sold * 100 / SALE_BASE);
        }

        #[test]
        fn price_rises_as_the_curve_fills() {
            let first = buy(0, 0, 1_000_000_000);
            let mid = buy(first, 1_000_000_000, 1_000_000_000);
            assert!(mid < first, "the second buy should get less base: {mid} vs {first}");
        }

        #[test]
        fn a_round_trip_never_profits() {
            // Buy, then immediately sell it all back with no fee at all. The invariant plus
            // rounding has to leave the trader with less quote than they put in, or the curve
            // leaks.
            let spent = 500_000_000_000_000u128;
            let got = buy(0, 0, spent);
            let back = swap_out(VIRTUAL_QUOTE + spent, VIRTUAL_BASE - got, got).unwrap();
            assert!(back <= spent, "round trip returned {back} for {spent}");
        }

        #[test]
        fn a_buy_is_clamped_to_the_room_left() {
            // 1% fee, and only 99 units of room: the net lands on the room exactly and the fee
            // shrinks with it.
            let (taken, fee, net) = split_buy(1_000_000, 100, 99).unwrap();
            assert_eq!(net, 99);
            assert_eq!(fee, 1);
            assert_eq!(taken, 100);
            assert!(taken <= 1_000_000);
        }

        #[test]
        fn an_unclamped_buy_keeps_the_whole_amount() {
            let (taken, fee, net) = split_buy(1_000_000, 100, u64::MAX).unwrap();
            assert_eq!(taken, 1_000_000);
            assert_eq!(fee, 10_000);
            assert_eq!(net, 990_000);
        }

        #[test]
        fn isqrt_is_a_square_root() {
            for v in [0u128, 1, 2, 3, 4, 9, 10, 1 << 64, u128::MAX] {
                let r = isqrt(v);
                assert!(r.saturating_mul(r) <= v, "isqrt({v}) = {r} is too big");
                let next = r + 1;
                assert!(
                    next.checked_mul(next).map(|sq| sq > v).unwrap_or(true),
                    "isqrt({v}) = {r} is too small"
                );
            }
        }

        #[test]
        fn the_pool_opens_where_the_curve_closed() {
            // A pool seeded with the reserve and the migration supply has to open at the curve's
            // closing price, or the first trade after graduation is free money.
            let quote = GRADUATION as u64;
            let base = 200_000_000_000_000u64; // 200M at 6 decimals
            let sqrt_price = expected_sqrt_price(quote, base).unwrap();
            // Square it back. Shifting a Q64.64 root down by 32 and squaring lands on the price in
            // Q64.64 again, which is the form the ratio below is already in.
            let price = (sqrt_price >> 32) * (sqrt_price >> 32);
            let expected = ((quote as u128) << 64) / base as u128;
            assert!(within_one_percent(price, expected), "{price} vs {expected}");
        }

        #[test]
        fn the_pool_is_priced_on_what_it_receives() {
            // A fully sold curve has exactly the migration supply left, so the pool can only ever
            // hold that minus the tax. Pricing it any other way asks the vault for base it does not
            // have.
            let migration = 200_000_000_000_000u64;
            let seeded = net_of_tax(migration, 300).unwrap();
            assert_eq!(seeded, 194_000_000_000_000);
            assert_eq!(net_of_tax(migration, 0).unwrap(), migration);
            // rounded up, like the token program: a single unit still owes a whole unit of tax
            assert_eq!(tax_of(1, 300).unwrap(), 1);
            assert_eq!(tax_of(0, 300).unwrap(), 0);
            assert_eq!(tax_of(u64::MAX, 10_000).unwrap(), u64::MAX);

            let taxed = expected_sqrt_price(GRADUATION as u64, seeded).unwrap();
            let untaxed = expected_sqrt_price(GRADUATION as u64, migration).unwrap();
            assert!(taxed > untaxed, "a taxed pool opens dearer per token");
        }

        #[test]
        fn one_percent_is_the_whole_slack() {
            assert!(within_one_percent(100, 100));
            assert!(within_one_percent(100, 101));
            assert!(!within_one_percent(100, 102));
            assert!(!within_one_percent(0, 1));
        }

        #[test]
        fn no_amount_the_chain_can_hold_overflows() {
            // Every amount on the way in is a u64, and u64::MAX squared still fits in a u128, so
            // the multiply inside swap_out cannot overflow for any input the chain can express.
            let max = u64::MAX as u128;
            assert!(swap_out(max, max, max).is_ok());
            assert!(bps_of(u64::MAX, 10_000).is_ok());
            // Beyond that it has to fail loudly rather than wrap.
            assert!(swap_out(u128::MAX, 1, u128::MAX).is_err());
        }
    }
}

// --- state ---------------------------------------------------------------------------------------

#[account]
#[derive(InitSpace)]
pub struct Config {
    /// Owns these settings. Cannot touch a live curve or any curve's money.
    pub authority: Pubkey,
    /// Where curve fees go, and the platform's side of the graduated pool's fees.
    pub fee_recipient: Pubkey,
    /// Written onto every new mint as its withdraw-withheld authority: the wallet that collects the
    /// tax and pays it out to holders.
    pub withhold_authority: Pubkey,
    /// What every curve trades against. COOK on Cookie Chain.
    pub quote_mint: Pubkey,
    /// Taken from the quote leg of every trade, both directions.
    pub curve_fee_bps: u16,
    /// The creator's share of the locked pool position at graduation. The rest is the platform's.
    pub creator_lp_share_bps: u16,
    /// The tax rates a creator may pick from. A zero entry is an unused slot.
    pub tax_tiers: [u16; 4],
    /// Raise that closes the curve, in quote units.
    pub graduation_quote: u64,
    /// Base the curve may sell, in base units.
    pub sale_base: u64,
    /// Base reserved for the pool at graduation.
    pub migration_base: u64,
    /// Virtual reserves, which set the opening price and how steeply it climbs.
    pub virtual_quote: u64,
    pub virtual_base: u64,
    pub token_decimals: u8,
    pub paused: bool,
    pub bump: u8,
    pub launch_count: u64,
    /// The Cookiebox pool config a graduated curve opens its pool against. It fixes the pool's fee
    /// and its price range, so it is part of what a launch promises and belongs here rather than in
    /// whatever the crank feels like passing.
    pub damm_config: Pubkey,
    pub _reserved: [u8; RESERVED - 32],
}

impl Config {
    /// Everything a launch mints: what the curve sells plus what the pool is seeded with.
    pub fn total_supply(&self) -> u64 {
        self.sale_base.saturating_add(self.migration_base)
    }

    pub fn tax_allowed(&self, bps: u16) -> bool {
        bps > 0 && self.tax_tiers.contains(&bps)
    }
}

#[account]
#[derive(InitSpace)]
pub struct Curve {
    pub config: Pubkey,
    pub creator: Pubkey,
    pub mint: Pubkey,
    pub base_vault: Pubkey,
    pub quote_vault: Pubkey,
    /// Copied from the config at launch. A later config change must never reprice a live curve.
    pub virtual_base: u64,
    pub virtual_quote: u64,
    pub sale_base: u64,
    pub migration_base: u64,
    pub graduation_quote: u64,
    /// Base handed out so far, and quote in the reserve. Fees are not part of the reserve.
    pub base_sold: u64,
    pub quote_raised: u64,
    pub fees_quote: u64,
    pub tax_bps: u16,
    pub curve_fee_bps: u16,
    pub creator_lp_share_bps: u16,
    pub state: u8,
    pub created_at: i64,
    pub bump: u8,
    /// Set when the pool is opened. The position that holds the locked liquidity is the PDA of this
    /// mint, and the pool is the one that position belongs to, so this single key is enough to find
    /// the rest and enough to refuse a claim aimed at somebody else's position.
    pub position_nft_mint: Pubkey,
    pub _reserved: [u8; RESERVED - 32],
}

impl Curve {
    pub fn reserve_base(&self) -> Result<u128> {
        Ok((self
            .virtual_base
            .checked_sub(self.base_sold)
            .ok_or(LaunchError::MathOverflow)?) as u128)
    }

    pub fn reserve_quote(&self) -> Result<u128> {
        Ok((self
            .virtual_quote
            .checked_add(self.quote_raised)
            .ok_or(LaunchError::MathOverflow)?) as u128)
    }
}

// --- parameters ----------------------------------------------------------------------------------

#[derive(AnchorSerialize, AnchorDeserialize, Clone)]
pub struct ConfigParams {
    pub fee_recipient: Pubkey,
    pub withhold_authority: Pubkey,
    pub curve_fee_bps: u16,
    pub creator_lp_share_bps: u16,
    pub tax_tiers: [u16; 4],
    pub graduation_quote: u64,
    pub sale_base: u64,
    pub migration_base: u64,
    pub virtual_quote: u64,
    pub virtual_base: u64,
    pub token_decimals: u8,
    pub paused: bool,
    pub damm_config: Pubkey,
}

impl ConfigParams {
    fn validate(&self) -> Result<()> {
        require!(self.curve_fee_bps <= MAX_CURVE_FEE_BPS, LaunchError::BadConfig);
        require!(self.creator_lp_share_bps as u128 <= BPS, LaunchError::BadConfig);
        require!(self.graduation_quote > 0, LaunchError::BadConfig);
        require!(self.sale_base > 0, LaunchError::BadConfig);
        require!(self.virtual_quote > 0, LaunchError::BadConfig);
        // The virtual base has to exceed what the curve will ever sell, or the reserve hits zero
        // and the price goes to infinity mid-raise.
        require!(self.virtual_base > self.sale_base, LaunchError::BadConfig);
        require!(self.token_decimals <= 9, LaunchError::BadConfig);
        require!(self.migration_base > 0, LaunchError::BadConfig);
        require!(self.damm_config != Pubkey::default(), LaunchError::BadConfig);
        require!(self.tax_tiers.iter().any(|t| *t > 0), LaunchError::BadConfig);
        require!(
            self.tax_tiers.iter().all(|t| (*t as u128) < BPS),
            LaunchError::BadConfig
        );
        Ok(())
    }

    fn apply(&self, config: &mut Config) {
        config.fee_recipient = self.fee_recipient;
        config.withhold_authority = self.withhold_authority;
        config.curve_fee_bps = self.curve_fee_bps;
        config.creator_lp_share_bps = self.creator_lp_share_bps;
        config.tax_tiers = self.tax_tiers;
        config.graduation_quote = self.graduation_quote;
        config.sale_base = self.sale_base;
        config.migration_base = self.migration_base;
        config.virtual_quote = self.virtual_quote;
        config.virtual_base = self.virtual_base;
        config.token_decimals = self.token_decimals;
        config.paused = self.paused;
        config.damm_config = self.damm_config;
    }
}

#[derive(AnchorSerialize, AnchorDeserialize, Clone)]
pub struct LaunchParams {
    pub name: String,
    pub symbol: String,
    pub uri: String,
    /// The tax, in basis points, chosen by the creator from the config's tiers. Frozen forever.
    pub tax_bps: u16,
}

// --- mint creation -------------------------------------------------------------------------------

/// Build the mint by hand, because Anchor cannot.
///
/// `#[account(init, mint::..)]` sizes the account for a bare mint, and extension space has to be
/// allocated before `initialize_mint2` runs. So the account is created here at the right length, the
/// two extensions are initialized into it, and only then does it become a mint.
///
/// The order is not cosmetic: the transfer fee goes in first with no config authority at all, so
/// there is never a moment, not even within this instruction, when the rate could be changed.
fn create_taxed_mint(ctx: &Context<Launch>, tax_bps: u16) -> Result<()> {
    let space = spl_token_2022::extension::ExtensionType::try_calculate_account_len::<
        spl_token_2022::state::Mint,
    >(&[
        spl_token_2022::extension::ExtensionType::TransferFeeConfig,
        spl_token_2022::extension::ExtensionType::MetadataPointer,
    ])?;
    let lamports = Rent::get()?.minimum_balance(space);

    system_program::create_account(
        CpiContext::new(
            ctx.accounts.system_program.to_account_info(),
            system_program::CreateAccount {
                from: ctx.accounts.creator.to_account_info(),
                to: ctx.accounts.mint.to_account_info(),
            },
        ),
        lamports,
        space as u64,
        &spl_token_2022::ID,
    )?;

    invoke(
        &spl_token_2022::extension::transfer_fee::instruction::initialize_transfer_fee_config(
            &spl_token_2022::ID,
            &ctx.accounts.mint.key(),
            None,
            Some(&ctx.accounts.config.withhold_authority),
            tax_bps,
            MAX_TRANSFER_FEE,
        )?,
        &[ctx.accounts.mint.to_account_info()],
    )?;

    invoke(
        &spl_token_2022::extension::metadata_pointer::instruction::initialize(
            &spl_token_2022::ID,
            &ctx.accounts.mint.key(),
            None,
            Some(ctx.accounts.mint.key()),
        )?,
        &[ctx.accounts.mint.to_account_info()],
    )?;

    invoke(
        &spl_token_2022::instruction::initialize_mint2(
            &spl_token_2022::ID,
            &ctx.accounts.mint.key(),
            &ctx.accounts.curve.key(),
            None,
            ctx.accounts.config.token_decimals,
        )?,
        &[ctx.accounts.mint.to_account_info()],
    )?;

    Ok(())
}

/// Write the name, symbol and link into the mint itself, then pay for the space that took.
///
/// The update authority is the curve, and the program has no instruction that uses it, so the
/// metadata is immutable in practice. That is deliberate: a token that can be renamed after people
/// have bought it is a token that can be turned into something else.
fn write_metadata(ctx: &Context<Launch>, params: &LaunchParams, seeds: &[&[u8]]) -> Result<()> {
    token_interface::token_metadata_initialize(
        CpiContext::new_with_signer(
            ctx.accounts.token_program.to_account_info(),
            TokenMetadataInitialize {
                program_id: ctx.accounts.token_program.to_account_info(),
                mint: ctx.accounts.mint.to_account_info(),
                metadata: ctx.accounts.mint.to_account_info(),
                mint_authority: ctx.accounts.curve.to_account_info(),
                update_authority: ctx.accounts.curve.to_account_info(),
            },
            &[seeds],
        ),
        params.name.clone(),
        params.symbol.clone(),
        params.uri.clone(),
    )?;

    // The instruction above reallocs the mint, and a reallocated account still has to be rent
    // exempt.
    let mint = ctx.accounts.mint.to_account_info();
    let needed = Rent::get()?.minimum_balance(mint.data_len());
    let short = needed.saturating_sub(mint.get_lamports());
    if short > 0 {
        system_program::transfer(
            CpiContext::new(
                ctx.accounts.system_program.to_account_info(),
                system_program::Transfer {
                    from: ctx.accounts.creator.to_account_info(),
                    to: mint,
                },
            ),
            short,
        )?;
    }
    Ok(())
}

/// The curve's two token accounts. Created here rather than by a constraint, because the base mint
/// does not exist yet when Anchor resolves constraints.
fn open_vaults(ctx: &Context<Launch>) -> Result<()> {
    anchor_spl::associated_token::create(CpiContext::new(
        ctx.accounts.associated_token_program.to_account_info(),
        anchor_spl::associated_token::Create {
            payer: ctx.accounts.creator.to_account_info(),
            associated_token: ctx.accounts.base_vault.to_account_info(),
            authority: ctx.accounts.vault_authority.to_account_info(),
            mint: ctx.accounts.mint.to_account_info(),
            system_program: ctx.accounts.system_program.to_account_info(),
            token_program: ctx.accounts.token_program.to_account_info(),
        },
    ))?;

    anchor_spl::associated_token::create(CpiContext::new(
        ctx.accounts.associated_token_program.to_account_info(),
        anchor_spl::associated_token::Create {
            payer: ctx.accounts.creator.to_account_info(),
            associated_token: ctx.accounts.quote_vault.to_account_info(),
            authority: ctx.accounts.vault_authority.to_account_info(),
            mint: ctx.accounts.quote_mint.to_account_info(),
            system_program: ctx.accounts.system_program.to_account_info(),
            token_program: ctx.accounts.quote_token_program.to_account_info(),
        },
    ))?;
    Ok(())
}

/// Mint the whole supply into the curve, then throw the key away.
fn mint_supply_and_seal(ctx: &Context<Launch>, supply: u64, seeds: &[&[u8]]) -> Result<()> {
    token_interface::mint_to(
        CpiContext::new_with_signer(
            ctx.accounts.token_program.to_account_info(),
            token_interface::MintTo {
                mint: ctx.accounts.mint.to_account_info(),
                to: ctx.accounts.base_vault.to_account_info(),
                authority: ctx.accounts.curve.to_account_info(),
            },
            &[seeds],
        ),
        supply,
    )?;

    token_interface::set_authority(
        CpiContext::new_with_signer(
            ctx.accounts.token_program.to_account_info(),
            token_interface::SetAuthority {
                current_authority: ctx.accounts.curve.to_account_info(),
                account_or_mint: ctx.accounts.mint.to_account_info(),
            },
            &[seeds],
        ),
        spl_token_2022::instruction::AuthorityType::MintTokens,
        None,
    )?;
    Ok(())
}

// --- accounts ------------------------------------------------------------------------------------

#[derive(Accounts)]
pub struct InitializeConfig<'info> {
    #[account(
        init,
        payer = authority,
        space = 8 + Config::INIT_SPACE,
        seeds = [CONFIG_SEED],
        bump,
    )]
    pub config: Box<Account<'info, Config>>,
    #[account(mut)]
    pub authority: Signer<'info>,
    pub quote_mint: Box<InterfaceAccount<'info, Mint>>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct UpdateConfig<'info> {
    #[account(mut, seeds = [CONFIG_SEED], bump = config.bump, has_one = authority)]
    pub config: Box<Account<'info, Config>>,
    pub authority: Signer<'info>,
}

#[derive(Accounts)]
pub struct Launch<'info> {
    #[account(mut, seeds = [CONFIG_SEED], bump = config.bump)]
    pub config: Box<Account<'info, Config>>,

    #[account(
        init,
        payer = creator,
        space = 8 + Curve::INIT_SPACE,
        seeds = [CURVE_SEED, mint.key().as_ref()],
        bump,
    )]
    pub curve: Box<Account<'info, Curve>>,

    /// The mint to be. Created inside the instruction, so it arrives as a fresh keypair that has
    /// signed for its own address and nothing else.
    #[account(mut)]
    pub mint: Signer<'info>,

    /// CHECK: holds this curve's assets and pays for its pool. Data-less on purpose, see
    /// `VaultAuthority`.
    #[account(mut, seeds = [AUTHORITY_SEED, mint.key().as_ref()], bump)]
    pub vault_authority: UncheckedAccount<'info>,

    /// CHECK: created in the instruction once the mint exists, at the address the associated token
    /// program derives for the vault authority.
    #[account(mut)]
    pub base_vault: UncheckedAccount<'info>,
    /// CHECK: as above, for the quote side.
    #[account(mut)]
    pub quote_vault: UncheckedAccount<'info>,

    #[account(address = config.quote_mint)]
    pub quote_mint: Box<InterfaceAccount<'info, Mint>>,

    #[account(mut)]
    pub creator: Signer<'info>,

    pub token_program: Interface<'info, TokenInterface>,
    pub quote_token_program: Interface<'info, TokenInterface>,
    pub associated_token_program: Program<'info, AssociatedToken>,
    pub system_program: Program<'info, System>,
}

#[derive(Accounts)]
pub struct Trade<'info> {
    #[account(seeds = [CONFIG_SEED], bump = config.bump)]
    pub config: Box<Account<'info, Config>>,

    #[account(
        mut,
        seeds = [CURVE_SEED, curve.mint.as_ref()],
        bump = curve.bump,
        has_one = config,
        has_one = mint,
        has_one = base_vault,
        has_one = quote_vault,
    )]
    pub curve: Box<Account<'info, Curve>>,

    pub mint: Box<InterfaceAccount<'info, Mint>>,
    #[account(address = config.quote_mint)]
    pub quote_mint: Box<InterfaceAccount<'info, Mint>>,

    /// CHECK: signs for the vaults. Data-less, see `VaultAuthority`.
    #[account(seeds = [AUTHORITY_SEED, curve.mint.as_ref()], bump)]
    pub vault_authority: UncheckedAccount<'info>,

    #[account(mut)]
    pub base_vault: Box<InterfaceAccount<'info, TokenAccount>>,
    #[account(mut)]
    pub quote_vault: Box<InterfaceAccount<'info, TokenAccount>>,

    #[account(mut, token::mint = mint, token::authority = trader)]
    pub trader_base: Box<InterfaceAccount<'info, TokenAccount>>,
    #[account(mut, token::mint = quote_mint, token::authority = trader)]
    pub trader_quote: Box<InterfaceAccount<'info, TokenAccount>>,

    pub trader: Signer<'info>,

    pub token_program: Interface<'info, TokenInterface>,
    pub quote_token_program: Interface<'info, TokenInterface>,
}

impl<'info> Trade<'info> {
    fn quote_in_ctx(
        &self,
    ) -> CpiContext<'_, '_, '_, 'info, token_interface::TransferChecked<'info>> {
        CpiContext::new(
            self.quote_token_program.to_account_info(),
            token_interface::TransferChecked {
                from: self.trader_quote.to_account_info(),
                mint: self.quote_mint.to_account_info(),
                to: self.quote_vault.to_account_info(),
                authority: self.trader.to_account_info(),
            },
        )
    }

    fn base_in_ctx(&self) -> CpiContext<'_, '_, '_, 'info, token_interface::TransferChecked<'info>> {
        CpiContext::new(
            self.token_program.to_account_info(),
            token_interface::TransferChecked {
                from: self.trader_base.to_account_info(),
                mint: self.mint.to_account_info(),
                to: self.base_vault.to_account_info(),
                authority: self.trader.to_account_info(),
            },
        )
    }

    fn base_out_ctx<'a>(
        &self,
        seeds: &'a [&'a [&'a [u8]]],
    ) -> CpiContext<'a, 'a, 'a, 'info, token_interface::TransferChecked<'info>>
    where
        'info: 'a,
    {
        CpiContext::new_with_signer(
            self.token_program.to_account_info(),
            token_interface::TransferChecked {
                from: self.base_vault.to_account_info(),
                mint: self.mint.to_account_info(),
                to: self.trader_base.to_account_info(),
                authority: self.vault_authority.to_account_info(),
            },
            seeds,
        )
    }

    fn quote_out_ctx<'a>(
        &self,
        seeds: &'a [&'a [&'a [u8]]],
    ) -> CpiContext<'a, 'a, 'a, 'info, token_interface::TransferChecked<'info>>
    where
        'info: 'a,
    {
        CpiContext::new_with_signer(
            self.quote_token_program.to_account_info(),
            token_interface::TransferChecked {
                from: self.quote_vault.to_account_info(),
                mint: self.quote_mint.to_account_info(),
                to: self.trader_quote.to_account_info(),
                authority: self.vault_authority.to_account_info(),
            },
            seeds,
        )
    }
}

#[derive(Accounts)]
pub struct ClaimCurveFees<'info> {
    #[account(seeds = [CONFIG_SEED], bump = config.bump)]
    pub config: Box<Account<'info, Config>>,

    #[account(
        mut,
        seeds = [CURVE_SEED, curve.mint.as_ref()],
        bump = curve.bump,
        has_one = config,
        has_one = quote_vault,
    )]
    pub curve: Box<Account<'info, Curve>>,

    #[account(address = config.quote_mint)]
    pub quote_mint: Box<InterfaceAccount<'info, Mint>>,

    /// CHECK: signs for the vault. Data-less, see `VaultAuthority`.
    #[account(seeds = [AUTHORITY_SEED, curve.mint.as_ref()], bump)]
    pub vault_authority: UncheckedAccount<'info>,

    #[account(mut)]
    pub quote_vault: Box<InterfaceAccount<'info, TokenAccount>>,

    /// Fixed by the config, so it does not matter who sends this instruction.
    #[account(mut, token::mint = quote_mint, token::authority = config.fee_recipient)]
    pub recipient: Box<InterfaceAccount<'info, TokenAccount>>,

    pub quote_token_program: Interface<'info, TokenInterface>,
}

impl<'info> ClaimCurveFees<'info> {
    fn transfer_ctx<'a>(
        &self,
        seeds: &'a [&'a [&'a [u8]]],
    ) -> CpiContext<'a, 'a, 'a, 'info, token_interface::TransferChecked<'info>>
    where
        'info: 'a,
    {
        CpiContext::new_with_signer(
            self.quote_token_program.to_account_info(),
            token_interface::TransferChecked {
                from: self.quote_vault.to_account_info(),
                mint: self.quote_mint.to_account_info(),
                to: self.recipient.to_account_info(),
                authority: self.vault_authority.to_account_info(),
            },
            seeds,
        )
    }
}

#[derive(Accounts)]
pub struct Graduate<'info> {
    #[account(seeds = [CONFIG_SEED], bump = config.bump)]
    pub config: Box<Account<'info, Config>>,

    #[account(
        mut,
        seeds = [CURVE_SEED, curve.mint.as_ref()],
        bump = curve.bump,
        has_one = config,
        has_one = mint,
        has_one = base_vault,
        has_one = quote_vault,
    )]
    pub curve: Box<Account<'info, Curve>>,

    /// CHECK: pays the pool's rent and signs for the vaults. Data-less, see `VaultAuthority`.
    #[account(mut, seeds = [AUTHORITY_SEED, curve.mint.as_ref()], bump)]
    pub vault_authority: UncheckedAccount<'info>,

    #[account(mut)]
    pub mint: Box<InterfaceAccount<'info, Mint>>,
    #[account(address = config.quote_mint)]
    pub quote_mint: Box<InterfaceAccount<'info, Mint>>,

    #[account(mut)]
    pub base_vault: Box<InterfaceAccount<'info, TokenAccount>>,
    #[account(mut)]
    pub quote_vault: Box<InterfaceAccount<'info, TokenAccount>>,

    /// CHECK: checked by address against the config, which is what fixes the pool's fee and range.
    #[account(address = config.damm_config)]
    pub damm_config: UncheckedAccount<'info>,
    /// CHECK: the pool program's one authority account, checked by address.
    #[account(address = damm::POOL_AUTHORITY)]
    pub damm_pool_authority: UncheckedAccount<'info>,
    /// CHECK: created by the pool program, which derives and checks its own address.
    #[account(mut)]
    pub pool: UncheckedAccount<'info>,
    /// CHECK: as above.
    #[account(mut)]
    pub position: UncheckedAccount<'info>,
    /// The position NFT. A fresh keypair, and the only thing that identifies the locked liquidity
    /// afterwards, so it is written onto the curve.
    #[account(mut)]
    pub position_nft_mint: Signer<'info>,
    /// CHECK: derived and checked by the pool program.
    #[account(mut)]
    pub position_nft_account: UncheckedAccount<'info>,
    /// CHECK: the pool's own token accounts, derived and checked by the pool program.
    #[account(mut)]
    pub pool_base_vault: UncheckedAccount<'info>,
    /// CHECK: as above.
    #[account(mut)]
    pub pool_quote_vault: UncheckedAccount<'info>,
    /// CHECK: the pool program's event authority, checked by the pool program.
    pub damm_event_authority: UncheckedAccount<'info>,
    /// CHECK: checked by address.
    #[account(address = damm::PROGRAM_ID)]
    pub damm_program: UncheckedAccount<'info>,

    pub token_program: Interface<'info, TokenInterface>,
    pub quote_token_program: Interface<'info, TokenInterface>,
    /// The pool program takes this separately from the two token programs above, because it creates
    /// its position NFT with it whatever the pool's own tokens are.
    pub token_2022_program: Program<'info, Token2022>,
    pub system_program: Program<'info, System>,
}

impl<'info> Graduate<'info> {
    fn initialize_pool(&self, liquidity: u128, sqrt_price: u128, seeds: &[&[u8]]) -> Result<()> {
        let mut data = Vec::with_capacity(8 + 16 + 16 + 1);
        data.extend_from_slice(&damm::IX_INITIALIZE_POOL);
        data.extend_from_slice(&liquidity.to_le_bytes());
        data.extend_from_slice(&sqrt_price.to_le_bytes());
        data.push(0); // activation_point: None, so the pool is live as soon as it exists

        let accounts = vec![
            // creator: the position owner, which is this curve's authority and nobody else
            AccountMeta::new_readonly(self.vault_authority.key(), false),
            AccountMeta::new(self.position_nft_mint.key(), true),
            AccountMeta::new(self.position_nft_account.key(), false),
            // payer: the same authority, signing as a PDA of this program
            AccountMeta::new(self.vault_authority.key(), true),
            AccountMeta::new_readonly(self.damm_config.key(), false),
            AccountMeta::new_readonly(self.damm_pool_authority.key(), false),
            AccountMeta::new(self.pool.key(), false),
            AccountMeta::new(self.position.key(), false),
            AccountMeta::new_readonly(self.mint.key(), false),
            AccountMeta::new_readonly(self.quote_mint.key(), false),
            AccountMeta::new(self.pool_base_vault.key(), false),
            AccountMeta::new(self.pool_quote_vault.key(), false),
            AccountMeta::new(self.base_vault.key(), false),
            AccountMeta::new(self.quote_vault.key(), false),
            AccountMeta::new_readonly(self.token_program.key(), false),
            AccountMeta::new_readonly(self.quote_token_program.key(), false),
            AccountMeta::new_readonly(self.token_2022_program.key(), false),
            AccountMeta::new_readonly(self.system_program.key(), false),
            AccountMeta::new_readonly(self.damm_event_authority.key(), false),
            AccountMeta::new_readonly(self.damm_program.key(), false),
        ];

        invoke_signed(
            &Instruction { program_id: self.damm_program.key(), accounts, data },
            &[
                self.vault_authority.to_account_info(),
                self.position_nft_mint.to_account_info(),
                self.position_nft_account.to_account_info(),
                self.damm_config.to_account_info(),
                self.damm_pool_authority.to_account_info(),
                self.pool.to_account_info(),
                self.position.to_account_info(),
                self.mint.to_account_info(),
                self.quote_mint.to_account_info(),
                self.pool_base_vault.to_account_info(),
                self.pool_quote_vault.to_account_info(),
                self.base_vault.to_account_info(),
                self.quote_vault.to_account_info(),
                self.token_program.to_account_info(),
                self.quote_token_program.to_account_info(),
                self.token_2022_program.to_account_info(),
                self.system_program.to_account_info(),
                self.damm_event_authority.to_account_info(),
                self.damm_program.to_account_info(),
            ],
            &[seeds],
        )?;
        Ok(())
    }

    fn lock_liquidity(&self, liquidity: u128, seeds: &[&[u8]]) -> Result<()> {
        let mut data = Vec::with_capacity(8 + 16);
        data.extend_from_slice(&damm::IX_PERMANENT_LOCK);
        data.extend_from_slice(&liquidity.to_le_bytes());

        let accounts = vec![
            AccountMeta::new(self.pool.key(), false),
            AccountMeta::new(self.position.key(), false),
            AccountMeta::new_readonly(self.position_nft_account.key(), false),
            AccountMeta::new_readonly(self.vault_authority.key(), true),
            AccountMeta::new_readonly(self.damm_event_authority.key(), false),
            AccountMeta::new_readonly(self.damm_program.key(), false),
        ];

        invoke_signed(
            &Instruction { program_id: self.damm_program.key(), accounts, data },
            &[
                self.pool.to_account_info(),
                self.position.to_account_info(),
                self.position_nft_account.to_account_info(),
                self.vault_authority.to_account_info(),
                self.damm_event_authority.to_account_info(),
                self.damm_program.to_account_info(),
            ],
            &[seeds],
        )?;
        Ok(())
    }

    fn burn_leftover(&self, amount: u64, seeds: &[&[u8]]) -> Result<()> {
        token_interface::burn(
            CpiContext::new_with_signer(
                self.token_program.to_account_info(),
                token_interface::Burn {
                    mint: self.mint.to_account_info(),
                    from: self.base_vault.to_account_info(),
                    authority: self.vault_authority.to_account_info(),
                },
                &[seeds],
            ),
            amount,
        )
    }
}

#[derive(Accounts)]
pub struct ClaimPoolFees<'info> {
    #[account(seeds = [CONFIG_SEED], bump = config.bump)]
    pub config: Box<Account<'info, Config>>,

    #[account(
        seeds = [CURVE_SEED, curve.mint.as_ref()],
        bump = curve.bump,
        has_one = config,
        has_one = mint,
        has_one = base_vault,
        has_one = quote_vault,
        has_one = creator,
    )]
    pub curve: Box<Account<'info, Curve>>,

    /// CHECK: owns the position and signs for the vaults. Data-less, see `VaultAuthority`.
    #[account(seeds = [AUTHORITY_SEED, curve.mint.as_ref()], bump)]
    pub vault_authority: UncheckedAccount<'info>,

    pub mint: Box<InterfaceAccount<'info, Mint>>,
    #[account(address = config.quote_mint)]
    pub quote_mint: Box<InterfaceAccount<'info, Mint>>,

    #[account(mut)]
    pub base_vault: Box<InterfaceAccount<'info, TokenAccount>>,
    #[account(mut)]
    pub quote_vault: Box<InterfaceAccount<'info, TokenAccount>>,

    /// CHECK: the pool program checks that the position belongs to this pool.
    #[account(mut)]
    pub pool: UncheckedAccount<'info>,
    /// CHECK: the pool program derives this from the position NFT mint.
    #[account(mut)]
    pub position: UncheckedAccount<'info>,
    /// CHECK: matched against the mint written on the curve when the pool was opened, so a claim
    /// cannot be pointed at a position this curve does not own.
    pub position_nft_mint: UncheckedAccount<'info>,
    /// CHECK: derived and checked by the pool program.
    pub position_nft_account: UncheckedAccount<'info>,
    /// CHECK: the pool's own token accounts.
    #[account(mut)]
    pub pool_base_vault: UncheckedAccount<'info>,
    /// CHECK: as above.
    #[account(mut)]
    pub pool_quote_vault: UncheckedAccount<'info>,
    /// CHECK: the pool program's one authority account, checked by address.
    #[account(address = damm::POOL_AUTHORITY)]
    pub damm_pool_authority: UncheckedAccount<'info>,
    /// CHECK: the pool program's event authority.
    pub damm_event_authority: UncheckedAccount<'info>,
    /// CHECK: checked by address.
    #[account(address = damm::PROGRAM_ID)]
    pub damm_program: UncheckedAccount<'info>,

    /// CHECK: only its key is used, to check the creator's token accounts below.
    pub creator: UncheckedAccount<'info>,

    #[account(mut, token::mint = quote_mint, token::authority = creator)]
    pub creator_quote: Box<InterfaceAccount<'info, TokenAccount>>,
    #[account(mut, token::mint = quote_mint, token::authority = config.fee_recipient)]
    pub platform_quote: Box<InterfaceAccount<'info, TokenAccount>>,
    #[account(mut, token::mint = mint, token::authority = creator)]
    pub creator_base: Box<InterfaceAccount<'info, TokenAccount>>,
    #[account(mut, token::mint = mint, token::authority = config.fee_recipient)]
    pub platform_base: Box<InterfaceAccount<'info, TokenAccount>>,

    pub token_program: Interface<'info, TokenInterface>,
    pub quote_token_program: Interface<'info, TokenInterface>,
}

impl<'info> ClaimPoolFees<'info> {
    fn claim_position_fee(&self, seeds: &[&[u8]]) -> Result<()> {
        let accounts = vec![
            AccountMeta::new_readonly(self.damm_pool_authority.key(), false),
            AccountMeta::new_readonly(self.pool.key(), false),
            AccountMeta::new(self.position.key(), false),
            AccountMeta::new(self.base_vault.key(), false),
            AccountMeta::new(self.quote_vault.key(), false),
            AccountMeta::new(self.pool_base_vault.key(), false),
            AccountMeta::new(self.pool_quote_vault.key(), false),
            AccountMeta::new_readonly(self.mint.key(), false),
            AccountMeta::new_readonly(self.quote_mint.key(), false),
            AccountMeta::new_readonly(self.position_nft_account.key(), false),
            AccountMeta::new_readonly(self.vault_authority.key(), true),
            AccountMeta::new_readonly(self.token_program.key(), false),
            AccountMeta::new_readonly(self.quote_token_program.key(), false),
            AccountMeta::new_readonly(self.damm_event_authority.key(), false),
            AccountMeta::new_readonly(self.damm_program.key(), false),
        ];

        invoke_signed(
            &Instruction {
                program_id: self.damm_program.key(),
                accounts,
                data: damm::IX_CLAIM_POSITION_FEE.to_vec(),
            },
            &[
                self.damm_pool_authority.to_account_info(),
                self.pool.to_account_info(),
                self.position.to_account_info(),
                self.base_vault.to_account_info(),
                self.quote_vault.to_account_info(),
                self.pool_base_vault.to_account_info(),
                self.pool_quote_vault.to_account_info(),
                self.mint.to_account_info(),
                self.quote_mint.to_account_info(),
                self.position_nft_account.to_account_info(),
                self.vault_authority.to_account_info(),
                self.token_program.to_account_info(),
                self.quote_token_program.to_account_info(),
                self.damm_event_authority.to_account_info(),
                self.damm_program.to_account_info(),
            ],
            &[seeds],
        )?;
        Ok(())
    }

    fn pay_out(
        &self,
        creator_quote: u64,
        platform_quote: u64,
        creator_base: u64,
        platform_base: u64,
        seeds: &[&[u8]],
    ) -> Result<()> {
        let quote_decimals = self.quote_mint.decimals;
        let base_decimals = self.mint.decimals;
        for (amount, to) in [
            (creator_quote, self.creator_quote.to_account_info()),
            (platform_quote, self.platform_quote.to_account_info()),
        ] {
            if amount == 0 {
                continue;
            }
            token_interface::transfer_checked(
                CpiContext::new_with_signer(
                    self.quote_token_program.to_account_info(),
                    token_interface::TransferChecked {
                        from: self.quote_vault.to_account_info(),
                        mint: self.quote_mint.to_account_info(),
                        to,
                        authority: self.vault_authority.to_account_info(),
                    },
                    &[seeds],
                ),
                amount,
                quote_decimals,
            )?;
        }
        for (amount, to) in [
            (creator_base, self.creator_base.to_account_info()),
            (platform_base, self.platform_base.to_account_info()),
        ] {
            if amount == 0 {
                continue;
            }
            token_interface::transfer_checked(
                CpiContext::new_with_signer(
                    self.token_program.to_account_info(),
                    token_interface::TransferChecked {
                        from: self.base_vault.to_account_info(),
                        mint: self.mint.to_account_info(),
                        to,
                        authority: self.vault_authority.to_account_info(),
                    },
                    &[seeds],
                ),
                amount,
                base_decimals,
            )?;
        }
        Ok(())
    }
}

// --- events --------------------------------------------------------------------------------------

#[event]
pub struct ConfigInitialized {
    pub config: Pubkey,
    pub authority: Pubkey,
    pub quote_mint: Pubkey,
}

#[event]
pub struct ConfigUpdated {
    pub config: Pubkey,
}

#[event]
pub struct Launched {
    pub curve: Pubkey,
    pub mint: Pubkey,
    pub creator: Pubkey,
    pub tax_bps: u16,
    pub symbol: String,
}

/// One trade. The app reads these to draw a chart, so everything a candle needs is here rather than
/// spread across the account state before and after.
#[event]
pub struct Traded {
    pub curve: Pubkey,
    pub mint: Pubkey,
    pub trader: Pubkey,
    pub is_buy: bool,
    pub quote_amount: u64,
    pub base_amount: u64,
    pub fee: u64,
    pub quote_raised: u64,
    pub base_sold: u64,
    pub graduated: bool,
}

#[event]
pub struct Graduated {
    pub curve: Pubkey,
    pub mint: Pubkey,
    pub pool: Pubkey,
    pub position: Pubkey,
    pub position_nft_mint: Pubkey,
    pub quote_seeded: u64,
    pub base_seeded: u64,
    pub burned: u64,
    pub liquidity: u128,
}

#[event]
pub struct PoolFeesClaimed {
    pub curve: Pubkey,
    pub mint: Pubkey,
    pub quote_to_creator: u64,
    pub quote_to_platform: u64,
    pub base_to_creator: u64,
    pub base_to_platform: u64,
}

#[event]
pub struct FeesClaimed {
    pub curve: Pubkey,
    pub mint: Pubkey,
    pub amount: u64,
}

// --- errors --------------------------------------------------------------------------------------

#[error_code]
pub enum LaunchError {
    #[msg("arithmetic overflowed")]
    MathOverflow,
    #[msg("a config value is out of range")]
    BadConfig,
    #[msg("launches are paused")]
    LaunchesPaused,
    #[msg("that tax rate is not one of the offered tiers")]
    TaxTierNotOffered,
    #[msg("name, symbol or uri is empty or too long")]
    BadMetadata,
    #[msg("this curve is closed to trading")]
    CurveClosed,
    #[msg("amount must be greater than zero")]
    ZeroAmount,
    #[msg("the amount is too small to move anything")]
    AmountTooSmall,
    #[msg("the curve has no base left to sell")]
    CurveExhausted,
    #[msg("the trade would return less than you asked for")]
    SlippageExceeded,
    #[msg("the curve cannot pay out more quote than it holds")]
    CurveInsolvent,
    #[msg("there is nothing to claim")]
    NothingToClaim,
    #[msg("this curve has not reached its target yet")]
    NotGraduated,
    #[msg("this curve has no pool yet")]
    NotPooled,
    #[msg("the pool would not open at the price the curve closed at")]
    PriceMismatch,
    #[msg("the pool took a different amount than the curve raised")]
    SeedOutOfRange,
    #[msg("that is not this curve's position")]
    WrongPosition,
}
